### ISSUE TITLE
Cannot drag and drop on Chromium

### ISSUE THREAD

**Issue by vvo** [ericduran/chromeHAR#8] opened 2013-03-01 17:20 UTC
Using Ubuntu and chromium I can't drag and drop.

Any idea ? Can you add an import button instead

**Comment by joeledwards** [comment] 2013-03-08 05:39
I observed this same issue. Turns chrome just replaces the content of the window the the HAR's text.

**Comment by soxofaan** [comment] 2013-04-15 14:42
I have same problem
Chrome 26.0.1410.65 on Mac OS X

**Comment by soxofaan** [comment] 2013-04-15 15:31
I used git bisect and the first commit where drag and drop stops working for me is
commit 1ddae45e3c1576f0a3fe54256db47101bad0dc53
Author: Eric J. Duran eric.duran7@gmail.com
Date:   Fri Oct 26 18:43:55 2012 -0400

```
Removing global functions and using angular modules and custom DND Directives
```

It works when I check out the commit before that one:
commit 7a657032706cba0b5a1caa8b3586c65b35b2e62a
Author: Eric J. Duran eric.duran7@gmail.com
Date:   Wed Sep 26 01:53:31 2012 -0400

```
Using strict and moving to a named closure
```

**Comment by ericduran** [comment] 2013-04-22 14:41
Oh nice, I should fix this.

**Comment by ericduran** [comment] 2013-04-27 15:11
This should be fixed now. Thanks for the debugging :)

**Closed as completed by ericduran** 2013-04-27 15:11 UTC

**Comment by soxofaan** [comment] 2013-04-27 20:11
Confirmed, works for me.

Great, thanks!
